In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('ESTB2021.csv', sep=';')
df.head()

C:\Users\thiago.silva\AppData\Local\Temp\ipykernel_2932\2009483420.py:1: DtypeWarning: Columns (3,4,21) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('ESTB2021.csv', sep=';')

,Bairros SP,Bairros Fortaleza,Bairros RJ,CNAE 2.0 Classe,CNAE 95 Classe,Distritos SP,Qtd Vínculos CLT,Qtd Vínculos Ativos,Qtd Vínculos Estatutários,Ind Atividade Ano,...,Natureza Jurídica,Regiões Adm DF,CNAE 2.0 Subclasse,Tamanho Estabelecimento,Tipo Estab,Tipo Estab.1,UF,IBGE Subsetor,CEP Estab,Ano
0,{ñ class},{ñ class},{ñ class},47296,52299,{ñ clas,7,7,0,1,...,2135,0,4729699,3,1,Cnpj,11,16,76963754,2021
1,{ñ class},{ñ class},{ñ class},47296,52299,{ñ clas,0,0,0,1,...,2135,0,4729699,1,1,Cnpj,11,16,76963888,2021
2,{ñ class},{ñ class},{ñ class},49302,60267,{ñ clas,1,1,0,1,...,2135,0,4930201,2,1,Cnpj,11,20,76847000,2021
3,{ñ class},{ñ class},{ñ class},47521,52450,{ñ clas,0,0,0,1,...,2135,0,4752100,1,1,Cnpj,11,16,76980090,2021
4,{ñ class},{ñ class},{ñ class},45111,50105,{ñ clas,41,41,0,1,...,2062,0,4511101,5,1,Cnpj,11,16,76821013,2021

In [3]:
df.count()

Bairros SP                   8472949
Bairros Fortaleza            8472949
Bairros RJ                   8472949
CNAE 2.0 Classe              8472949
CNAE 95 Classe               8472949
Distritos SP                 8472949
Qtd Vínculos CLT             8472949
Qtd Vínculos Ativos          8472949
Qtd Vínculos Estatutários    8472949
Ind Atividade Ano            8472949
Ind CEI Vinculado            8472949
Ind Estab Participa PAT      8472949
Ind Rais Negativa            8472949
Ind Simples                  8472949
Município                    8472949
Natureza Jurídica            8472949
Regiões Adm DF               8472949
CNAE 2.0 Subclasse           8472949
Tamanho Estabelecimento      8472949
Tipo Estab                   8472949
Tipo Estab.1                 8472949
UF                           8472949
IBGE Subsetor                8472949
CEP Estab                    8472949
Ano                          8472949
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8472949 entries, 0 to 8472948
Data columns (total 25 columns):
 #   Column                     Dtype
---  ------                     -----
 0   Bairros SP                 object
 1   Bairros Fortaleza          object
 2   Bairros RJ                 object
 3   CNAE 2.0 Classe            object
 4   CNAE 95 Classe             object
 5   Distritos SP               object
 6   Qtd Vínculos CLT           int64
 7   Qtd Vínculos Ativos        int64
 8   Qtd Vínculos Estatutários  int64
 9   Ind Atividade Ano          int64
 10  Ind CEI Vinculado          int64
 11  Ind Estab Participa PAT    int64
 12  Ind Rais Negativa          int64
 13  Ind Simples                int64
 14  Município                  int64
 15  Natureza Jurídica          int64
 16  Regiões Adm DF             int64
 17  CNAE 2.0 Subclasse         int64
 18  Tamanho Estabelecimento    int64
 19  Tipo Estab                 int64
 20  Tipo Estab.1               object
 21  UF                         object
 22  IBGE Subsetor              int64
 23  CEP Estab                  int64
 24  Ano                        int64
dtypes: int64(17), object(8)
memory usage: 1.6+ GB

In [58]:
df_agg = df.groupby('UF')['Qtd Vínculos Ativos'].sum()

In [59]:
df_agg.to_csv('rais2021_uf_agg.csv', index=True) # Defina o nome do arquivo desejado

In [60]:
df_agg = pd.read_csv('rais2021_uf_agg.csv', sep=',')

In [63]:
# Dicionário de mapeamento de códigos de UF para siglas dos estados
uf_siglas = {
    '11': 'RO', '12': 'AC', '13': 'AM', '14': 'RR', '15': 'PA', '16': 'AP', '17': 'TO',
    '21': 'MA', '22': 'PI', '23': 'CE', '24': 'RN', '25': 'PB', '26': 'PE', '27': 'AL', '28': 'SE', '29': 'BA',
    '31': 'MG', '32': 'ES', '33': 'RJ', '35': 'SP',
    '41': 'PR', '42': 'SC', '43': 'RS',
    '50': 'MS', '51': 'MT', '52': 'GO', '53': 'DF'
}

# Dicionário de mapeamento de códigos de UF para nomes dos estados
uf_nomes = {
    '11': 'Rondônia', '12': 'Acre', '13': 'Amazonas', '14': 'Roraima', '15': 'Pará', '16': 'Amapá', '17': 'Tocantins',
    '21': 'Maranhão', '22': 'Piauí', '23': 'Ceará', '24': 'Rio Grande do Norte', '25': 'Paraíba',
    '26': 'Pernambuco', '27': 'Alagoas', '28': 'Sergipe', '29': 'Bahia',
    '31': 'Minas Gerais', '32': 'Espírito Santo', '33': 'Rio de Janeiro', '35': 'São Paulo',
    '41': 'Paraná', '42': 'Santa Catarina', '43': 'Rio Grande do Sul',
    '50': 'Mato Grosso do Sul', '51': 'Mato Grosso', '52': 'Goiás', '53': 'Distrito Federal'
}

# Adicionar coluna com siglas dos estados
df_agg['Sigla'] = df_agg['UF'].map(uf_siglas)

# Adicionar coluna com nomes dos estados
df_agg['Estado'] = df_agg['UF'].map(uf_nomes)

In [42]:
df_agg.to_csv('rais2021_uf_agg.csv', index=True) # Defina o nome do arquivo desejado